version: '3.8'

services:
  emails:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/emails/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/emails
        - IMAGE_DESCRIPTION="The emails service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}emails${DOCKER_TAG}'
  rate-limit:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/rate-limit/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/rate-limit
        - IMAGE_DESCRIPTION="The rate limit service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}rate-limit${DOCKER_TAG}'
  schema:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/schema/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/schema
        - IMAGE_DESCRIPTION="The schema service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}schema${DOCKER_TAG}'
  server:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/server/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/server
        - IMAGE_DESCRIPTION="The server service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}server${DOCKER_TAG}'
  storage:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/storage/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/storage
        - IMAGE_DESCRIPTION="The storage service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}storage${DOCKER_TAG}'
  stripe-billing:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/stripe-billing/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/stripe-billing
        - IMAGE_DESCRIPTION="The stripe billing service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}stripe-billing${DOCKER_TAG}'
  tokens:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/tokens/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/tokens
        - IMAGE_DESCRIPTION="The tokens service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}tokens${DOCKER_TAG}'
  usage-estimator:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/usage-estimator/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/usage-estimator
        - IMAGE_DESCRIPTION="The usage estimator service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}usage-estimator${DOCKER_TAG}'
  usage-ingestor:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/usage-ingestor/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/usage-ingestor
        - IMAGE_DESCRIPTION="The usage ingestor service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}usage-ingestor${DOCKER_TAG}'
  usage:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/usage/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/usage
        - IMAGE_DESCRIPTION="The usage service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}usage${DOCKER_TAG}'
  webhooks:
    build:
      dockerfile: '${PWD:-.}/services.dockerfile'
      context: '${PWD:-.}/packages/services/webhooks/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/webhooks
        - IMAGE_DESCRIPTION="The webhooks service of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}webhooks${DOCKER_TAG}'
  app:
    build:
      dockerfile: '${PWD:-.}/app.dockerfile'
      context: '${PWD:-.}/packages/web/app/dist'
      args:
        - RELEASE=${RELEASE:-dev}
        - IMAGE_TITLE=graphql-hive/app
        - IMAGE_DESCRIPTION="The app of the GraphQL Hive project."
    image: '${DOCKER_REGISTRY}app${DOCKER_TAG}'
