packages:
  - packages/internal/*
  - packages/services/demo/*
  - packages/services/*
  - packages/migrations
  - packages/services/external-composition/*
  - packages/web/*
  - packages/libraries/*
  - integration-tests
  - deployment
  - scripts
  - rules
  - load-tests/otel-traces

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'envelop'
  - '@envelop/*'
  - 'graphql-yoga'
  - '@graphql-yoga/*'
  - 'graphql-hive/*'
  - '@graphql-inspector/*'
  - '@graphql-tools/*'
  - '@whatwg-node/*'
  - '@theguild/federation-composition'
  - graphql-modules
  - 'react-foundry'
  - '@eddeee888/gcg-server-config@0.6.0' # TODO: eddeee888 remove when minimumReleaseAge passes
  - '@eddeee888/gcg-typescript-resolver-files@0.18.0' # TODO: eddeee888 remove when minimumReleaseAge passes
