packages:
  - packages/internal/*
  - packages/services/demo/*
  - packages/services/*
  - packages/migrations
  - packages/services/external-composition/*
  - packages/web/*
  - packages/libraries/*
  - integration-tests
  - deployment
  - scripts
  - rules
  - load-tests/otel-traces

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'envelop'
  - '@envelop/*'
  - 'graphql-yoga'
  - '@graphql-yoga/*'
  - 'graphql-hive/*'
  - '@graphql-inspector/*'
  - '@graphql-tools/*'
  - '@theguild/federation-composition'
