import { exec } from 'child_process';
import { readFileSync } from 'fs';
import ci from 'env-ci';

interface CIRunner {
  detect(): boolean;
  env(): Promise<{
    commits: string[];
    pullRequestNumber: string | undefined | null;
    repository: string | undefined | null;
  }>;
}

const splitBy = '<##>';
const gitLogFormat = [
  /* full hash */ '%H',
  /* Author's name */ '%an',
  /* Author's email */ '%ae',
].join(splitBy);
const latestCommitCommand = `git log -1 --pretty=format:"${gitLogFormat}"`;

function getLatestCommitFromGit() {
  return new Promise<{
    hash: string;
    author: string;
  } | null>(resolve => {
    exec(latestCommitCommand, { cwd: process.cwd() }, (_, stdout) => {
      if (stdout.includes(splitBy)) {
        const [hash, authorName, authorEmail] = stdout.split(splitBy);
        if (hash && authorName) {
          let author = authorName;

          if (authorEmail) {
            author += ` <${authorEmail}>`;
          }

          resolve({
            hash,
            author,
          });
          return;
        }
      }

      resolve(null);
    });
  });
}

function getMergeGroupCommits(baseSha: string, headSha: string): Promise<string[]> {
  return new Promise<string[]>(resolve => {
    // We use --no-merges to ignore the temporary merge commit generated by the queue
    exec(
      `git rev-list --no-merges ${baseSha}..${headSha}`,
      { cwd: process.cwd() },
      (error, stdout) => {
        if (error) {
          resolve([]);
          return;
        }

        const commits = stdout
          .split('\n')
          .map(c => c.trim())
          .filter(Boolean);
        resolve(commits);
      },
    );
  });
}

function useGitHubAction(): CIRunner {
  return {
    detect() {
      // eslint-disable-next-line no-process-env
      return !!process.env.GITHUB_ACTIONS;
    },
    async env() {
      // eslint-disable-next-line no-process-env
      const repository = process.env['GITHUB_REPOSITORY'] ?? null;
      let pullRequestNumber: string | null = null;
      let commits: string[] = [];

      // eslint-disable-next-line no-process-env
      const eventName = process.env.GITHUB_EVENT_NAME;

      const isPr = eventName === 'pull_request' || eventName === 'pull_request_target';
      const isMergeGroup = eventName === 'merge_group';

      if (isPr || isMergeGroup) {
        try {
          // eslint-disable-next-line no-process-env
          const event = process.env.GITHUB_EVENT_PATH
            ? // eslint-disable-next-line no-process-env
              JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, 'utf-8'))
            : undefined;

          if (isPr && event?.pull_request) {
            commits = [event.pull_request.head.sha as string];
            pullRequestNumber = String(event.pull_request.number);
          } else if (isMergeGroup && event?.merge_group) {
            const baseSha = event.merge_group.base_sha as string;
            const headSha = event.merge_group.head_sha as string;

            if (baseSha && headSha) {
              commits = await getMergeGroupCommits(baseSha, headSha);
            }
          }
        } catch {
          // Noop
        }
      }

      return { commits, pullRequestNumber, repository };
    },
  };
}

export type GitInfo = {
  repository: string | null;
  pullRequestNumber: string | null;
  commits: string[];
  author: string | null;
};

export async function gitInfo(noGit: () => void): Promise<GitInfo> {
  let repository: string | null = null;
  let pullRequestNumber: string | null = null;
  let commits: string[] = [];
  let author: string | null = null;

  const env = ci();

  const githubAction = useGitHubAction();

  if (githubAction.detect()) {
    const ghEnv = await githubAction.env();
    repository = ghEnv.repository ?? null;
    commits = ghEnv.commits ?? [];
    pullRequestNumber = ghEnv.pullRequestNumber ?? null;
  }

  // Fallback to env-ci commit if empty
  if (commits.length === 0 && env.commit) {
    commits = [env.commit];
  }

  // Fallback to latest local commit if still empty, and fetch author
  if (commits.length === 0 || !author) {
    const git = await getLatestCommitFromGit();
    if (git) {
      if (commits.length === 0) {
        commits = [git.hash];
      }

      if (!author) {
        author = git.author;
      }
    } else {
      noGit();
    }
  }

  return {
    repository,
    pullRequestNumber,
    commits,
    author,
  };
}
