apiVersion: 1

datasources:
  - name: Local Prometheus
    type: prometheus
    uid: local-prom
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: Local Tempo
    type: tempo
    uid: local-tempo
    url: http://tempo:3200
    access: proxy
