{
 "title": "Hive Tokens Metrics",
 "tags": [
  "hive",
  "tokens"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(tokens_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET / throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(tokens_http_requests_total[$__range]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tokens_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(tokens_reads_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(tokens_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(tokens_cache_reads_total[$__rate_interval])) - sum(rate(tokens_cache_reads_total{status=\"miss\"}[$__rate_interval]))) / sum(rate(tokens_cache_reads_total[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Reads from cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(tokens_cache_reads_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(tokens_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(tokens_cache_reads_total{status=\"miss\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(tokens_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "In-Memory Cache fill ups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(source) (rate(tokens_cache_fills_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale cache hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(tokens_cache_reads_total{status=\"stale\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(tokens_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  }
 ]
}