{
 "title": "Hive Vitals Overview",
 "tags": [
  "overview",
  "hive"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Resources Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Balancer SNAT Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Used SNAT Ports",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [],
      "metricName": "UsedSnatPorts",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resourceGroup": "AZURE_LB_RESOURCE_GROUP",
      "resourceName": "kubernetes",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "SNAT Connection Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SnatConnectionCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resourceGroup": "AZURE_LB_RESOURCE_GROUP",
      "resourceName": "kubernetes",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Postgres Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU %",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "RAM %",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "IOPS Avg",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Storage %",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Max",
      "allowedTimeGrainsMs": [
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "max_connections",
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Active",
      "allowedTimeGrainsMs": [
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "active_connections",
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Waiting",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "client_connections_waiting",
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Kafka Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "AZURE_EVENTHUB_RESOURCE_GROUP",
      "resourceName": "AZURE_EVENTHUB_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Outgoing Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "AZURE_EVENTHUB_RESOURCE_GROUP",
      "resourceName": "AZURE_EVENTHUB_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Kubernetes Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU % Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "resourceGroup": "AZURE_KUBERNETES_RESOURCE_GROUP",
      "resourceName": "AZURE_KUBERNETES_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "RAM % Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_memory_rss_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "resourceGroup": "AZURE_KUBERNETES_RESOURCE_GROUP",
      "resourceName": "AZURE_KUBERNETES_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"usage-.*\"}",
     "legendFormat": "Process Memory - {{pod}}"
    }
   ]
  },
  { "title": "Services CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Usage Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"usage-service-.*\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Usage Ingestor Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"usage-ingestor-service-.*\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Schema service memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"schema-.*\"}"
    }
   ]
  },
  {
   "title": "Schema Service CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"schema-.*\"}[$__range])"
    }
   ]
  }
 ]
}