{
 "title": "Schema Registry",
 "tags": [
  "hive",
  "schema-registry"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Publish", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Conclusion over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (conclusion) (rate(registry_publish_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model) (rate(registry_publish_count_total[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "By model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(model) (rate(registry_publish_count_total[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "By model and project",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model, projectType) (rate(registry_publish_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}} ({{model}})"
    }
   ]
  },
  {
   "title": "By project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(projectType) (rate(registry_publish_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}}"
    }
   ]
  },
  {
   "title": "By model and project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(model, projectType) (rate(registry_publish_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}} ({{model}})"
    }
   ]
  },
  { "title": "Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Conclusion over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (conclusion) (rate(registry_check_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model) (rate(registry_check_count_total[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "By model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(model) (rate(registry_check_count_total[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "By model and project",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model, projectType) (rate(registry_check_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}} ({{model}})"
    }
   ]
  },
  {
   "title": "By project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(projectType) (rate(registry_check_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}}"
    }
   ]
  },
  {
   "title": "By model and project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(model, projectType) (rate(registry_check_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}} ({{model}})"
    }
   ]
  },
  { "title": "Delete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "By model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model) (rate(registry_delete_count_total[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "By model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(model) (rate(registry_delete_count_total[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Schema Checks bB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model, projectType) (rate(registry_delete_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}} ({{model}})"
    }
   ]
  },
  {
   "title": "By project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(projectType) (rate(registry_delete_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}}"
    }
   ]
  },
  {
   "title": "By model and project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(model, projectType) (rate(registry_delete_count_total[$__rate_interval]))",
     "legendFormat": "{{projectType}} ({{model}})"
    }
   ]
  }
 ]
}