{
 "title": "Performance Traces",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "postgresThreshold", "label": "Postgres Threshold", "query": "3000ms,5000ms,10000ms" },
   { "name": "clickhouseThreshold", "label": "Clickhouse Threshold", "query": "1000ms,3000ms,5000ms,10000ms" },
   { "name": "schemaCheckThreshold", "label": "Schema Check Threshold", "query": "1000ms,3000ms,5000ms,10000ms" },
   { "name": "schemaPublishThreshold", "label": "Schema Publish Threshold", "query": "1000ms,3000ms,5000ms,10000ms" },
   {
    "name": "requestsThreshold",
    "label": "HTTP Requests Threshold",
    "query": "1000ms,3000ms,5000ms,10000ms,20000ms"
   }
  ]
 },
 "panels": [
  {
   "title": "Slow Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Slow GraphQL HTTP Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "9d055a7f", "operator": "=", "scope": "span" }
     ],
     "limit": 100,
     "query": "{name=~\"POST /graphql\" && duration>$requestsThreshold}",
     "spss": 20,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Slow Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Slow SchemaPublisher.internalCheck",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "filters": [
      { "id": "9d055a7f", "operator": "=", "scope": "span" }
     ],
     "limit": 100,
     "query": "{name=\"SchemaPublisher.internalCheck\" && duration>$schemaCheckThreshold}",
     "spss": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Slow SchemaPublisher.publish",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "filters": [
      { "id": "9d055a7f", "operator": "=", "scope": "span" }
     ],
     "limit": 100,
     "query": "{name=~\"SchemaPublisher.publish\" && duration>$schemaPublishThreshold}",
     "spss": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Clickhouse Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Clickhouse Queries",
     "type": "table",
     "description": "A list of requests that included a slow Clickhouse query",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "filters": [
        { "id": "9d055a7f", "operator": "=", "scope": "span" }
       ],
       "limit": 100,
       "query": "{name=~\"ClickHouse: .*\" && duration>${clickhouseThreshold}}",
       "spss": 20,
       "tableType": "traces"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Postgres Queries",
     "type": "table",
     "description": "A list of requests that included a slow Postgres query",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "filters": [
        { "id": "9d055a7f", "operator": "=", "scope": "span" }
       ],
       "limit": 100,
       "query": "{name=~\"PG: .*\" && duration>${postgresThreshold}}",
       "spss": 20,
       "tableType": "traces"
      }
     ]
    }
   ]
  }
 ]
}