// THIS CODE WAS AUTOMATICALLY GENERATED BY @hive/docs in src/app/feed.xml/route.ts

export const latestChangelog = [
  {
    "date": "January 10, 2025",
    "href": "https://the-guild.dev/graphql/hive/product-updates/2025-01-10-static-breaking-change-threshold",
    "title": "Added a Conditional Breaking Change Static Threshold",
    "description": "A minor improvement to our conditional breaking changes behavior that allows changes to be considered breaking based on a minimum number of requests."
  },
  {
    "date": "December 27, 2024",
    "href": "https://the-guild.dev/graphql/hive/product-updates/2024-12-27-audit-logs",
    "title": "Audit Logs",
    "description": "Track actions within your organization."
  },
  {
    "date": "December 27, 2024",
    "href": "https://the-guild.dev/graphql/hive/product-updates/2024-12-27-preflight-script",
    "title": "Preflight Scripts in the Laboratory",
    "description": "Populate headers with environment variables and automate authentication flows for GraphQL requests."
  },
  {
    "date": "November 20, 2024",
    "href": "https://the-guild.dev/graphql/hive/product-updates/2024-11-20-hive-plugin-apollo-router-crate",
    "title": "Hive Plugin for Apollo-Router now available on Crates.io",
    "description": "We've published the Hive Plugin for Apollo-Router on Crates.io. Learn how to use it in your custom Apollo-Router projects."
  }
];
