extensions:
  hiveauth:
    endpoint: ${HIVE_OTEL_AUTH_ENDPOINT}
  health_check:
    endpoint: '0.0.0.0:13133'
receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: '0.0.0.0:4317'
        auth:
          authenticator: hiveauth
      http:
        cors:
          allowed_origins: ['*']
          allowed_headers: ['*']
        include_metadata: true
        endpoint: '0.0.0.0:4318'
        auth:
          authenticator: hiveauth
processors:
  attributes:
    actions:
      - key: hive.target_id
        from_context: auth.targetId
        action: insert
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
exporters:
  debug:
    verbosity: basic
  kafka:
    brokers:
      - ${KAFKA_BROKER}
    topic: otel-traces
    encoding: otlp_proto
    producer:
      compression: snappy
      max_message_bytes: 10485760 # 10MB
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
service:
  extensions:
    - hiveauth
    - health_check
  telemetry:
    logs:
      level: INFO
      encoding: json
      output_paths: ['stdout']
      error_output_paths: ['stderr']
    metrics:
      address: '0.0.0.0:10254'
      level: detailed
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - memory_limiter
        - attributes
      exporters:
        - kafka
        # - debug
