// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("hiveauth")
	ScopeName = "github.com/graphql-hive/console/docker/configs/otel-collector/extension-hiveauth"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
