[package]
name = "example-graphql-hive-async-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0.13"
async-graphql-axum = "7.0.13"
axum = "0.7.7"
hyper = "1.4.1"
tokio = { version = "1.40.0", features = ["full"] }
graphql-hive-async-graphql-extension = { path = "../", features = ["axum"] }
