export default {
  index: 'Schema Registry Introduction',
  'get-started': 'Getting Started',
  explorer: 'Schema Explorer',
  insights: 'Usage Insights',
  laboratory: 'Laboratory / Playground',
  management: 'Management',
  'high-availability-cdn': 'High-Availability CDN',
  'usage-reporting': 'Usage Reporting and Monitoring',
  contracts: 'Schema Contracts',
  'schema-policy': 'Schema Policies',
  'app-deployments': 'App Deployments (Persisted Documents)',
  'external-schema-composition': 'External Schema Composition',
  'self-hosting': 'Self-Hosting',
};
