name: CI
on: [pull_request]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:13.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Create Database
        working-directory: packages/services/storage
        run: yarn db:create

      - name: Migrate Database
        working-directory: packages/services/storage
        run: yarn db:migrator up

      - name: Generate Database Types
        working-directory: packages/services/storage
        run: yarn db:generate

      - name: Check if DB types were modified
        run: git diff --exit-code ./packages/services/storage/src/db/types.ts

      - name: Share node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Pull node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

      - name: Setup Turbo
        run: node ./scripts/turborepo-setup.js

      - name: Build
        run: yarn workspace integration-tests run build-and-pack
        env:
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.TEST_STRIPE_PUBLIC_KEY }}

      - name: Pull images
        run: docker-compose -f integration-tests/docker-compose.yml pull

      - name: Integration Tests
        run: yarn workspace integration-tests run dockest
        timeout-minutes: 15
        env:
          AUTH0_DOMAIN: ${{ secrets.TEST_AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
          AUTH0_USER_PASSWORD: ${{ secrets.AUTH0_TESTING_USER_PASSWORD }}
          AUTH0_USER_MAIN_EMAIL: contact@the-guild.dev
          AUTH0_USER_EXTRA_EMAIL: contact+extra@the-guild.dev
          AUTH0_SECRET: ${{ secrets.TEST_AUTH0_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
          AUTH0_CONNECTION: Username-Password-Authentication
          STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

      - name: Dockest logs
        if: always()
        run: cat integration-tests/*.log

  schema-check:
    name: Schema Check
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5

    env:
      HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Pull node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

      - name: Generate Types
        run: yarn graphql:generate

      - name: Check PR label
        if: contains(github.event.pull_request.labels.*.name, 'non-breaking')
        run: echo '::set-output name=SAFE_FLAG::--forceSafe'
        id: pr-label-check

      - name: Schema Check
        run: ./packages/libraries/cli/bin/dev schema:check "packages/services/api/src/modules/*/module.graphql.ts" ${{ steps.pr-label-check.outputs.SAFE_FLAG }} --github

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Pull node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

      - name: Generate Types
        run: yarn graphql:generate

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Pull node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

      - name: Setup Turbo
        run: node ./scripts/turborepo-setup.js

      - name: Generate Types
        run: yarn graphql:generate

      - name: Build
        run: yarn build

  rust_windows:
    name: Build Rust for Windows
    runs-on: windows-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v3
        with:
          name: router-win
          path: target/release/router.exe

  rust_macos:
    name: Build Rust for MacOS
    runs-on: macos-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Strip binary from debug symbols
        run: strip target/release/router

      - uses: actions/upload-artifact@v3
        with:
          name: router-macos
          path: target/release/router

  rust_linux:
    name: Build Rust for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1
        with:
          key: rust_linux_cross

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - name: Strip binary from debug symbols
        run: strip target/x86_64-unknown-linux-gnu/router

      - uses: actions/upload-artifact@v3
        with:
          name: router-linux
          path: target/x86_64-unknown-linux-musl/release/router

  rust_arm_binary:
    name: 'Build Rust ARM binary ${{ matrix.arch }}'
    strategy:
      matrix:
        include:
          - arch: arm64
            rust_target: aarch64-unknown-linux-musl
            docker_image: arm64v8/ubuntu
            docker_platform: aarch64
          - arch: arm32
            rust_target: armv7-unknown-linux-gnueabihf
            docker_image: arm32v7/ubuntu
            docker_platform: armv7

    runs-on: ubuntu-latest

    env:
      RUST_TARGET: ${{ matrix.rust_target }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          key: rust_arm_${{ matrix.arch }}

      - name: 'Download `cross` crate'
        run: cargo install cross

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build release'
        run: cross build --target $RUST_TARGET --release

      - name: Compress binary using UPX
        run: |
          sudo apt-get install -y upx
          upx target/$RUST_TARGET/release/router

      - uses: uraimo/run-on-arch-action@v2
        name: Sanity test
        with:
          arch: ${{matrix.docker_platform}}
          distro: ubuntu18.04
          dockerRunArgs: |
            --volume "${PWD}/target/${{matrix.rust_target}}/release:/artifacts"
          run: /artifacts/router --version

      - uses: actions/upload-artifact@v3
        with:
          name: router-${{ matrix.arch }}
          path: target/${{ env.RUST_TARGET }}/release/router

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Pull node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

      - name: ESLint cache
        uses: actions/cache@v2
        with:
          path: '.eslintcache'
          key: ${{ runner.os }}-eslint-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-eslint

      - name: Setup Turbo
        run: node ./scripts/turborepo-setup.js

      - name: Generate Types
        run: yarn graphql:generate

      - name: Type Check
        run: yarn typecheck

      - name: Lint ESLint
        run: yarn lint

      - name: Lint Prettier
        run: yarn lint:prettier
