on:
  workflow_call:
    secrets:
      hiveToken:
jobs:
  graphql-app-deployment-check:
    name: GraphQL App Deployment Check
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install Hive CLI
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
      - name: check documents
        env:
          HIVE_TOKEN: ${{ secrets.hiveToken }}
        run: |
          hive operations:check "./packages/web/app/src/(components|lib|pages)/**/*.ts(x)?" --globalGraphqlTag graphql
