on:
  workflow_call:

jobs:
  eslint-and-prettier:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup environment
        uses: ./.github/actions/setup

      - name: eslint cache
        uses: actions/cache@v3
        with:
          path: '.eslintcache'
          key: ${{ runner.os }}-eslint-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-eslint

      - name: eslint
        run: pnpm lint
        env:
          TIMING: 'true'
          DEBUG: 'eslint:cli-engine'

      - name: prettier
        run: pnpm lint:prettier

  operation-security:
    name: Operation Check
    runs-on: ubuntu-22.04

    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup environment
        uses: ./.github/actions/setup

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Pull node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ github.sha }}

      - name: Generate Types
        run: yarn graphql:generate

      - name: Check PR label
        if: contains(github.event.pull_request.labels.*.name, 'non-breaking')
        run: echo '::set-output name=SAFE_FLAG::--forceSafe'
        id: pr-label-check

      - name: Operation Check
        run: |
          pnpm graphql-inspector validate \
            "packages/web/app/**/*.graphql|packages/libraries/cli/**/*.graphql|packages/web/app/**/*.ts(x)" \
            "packages/**/module.graphql.ts" \
            --maxDepth=20 \
            --maxAliasCount=10 \
            --maxDirectiveCount=20 \
            --maxTokenCount=800
