name: ci
on:
  push:
    branches:
      - main

concurrency:
  group: ci-main
  cancel-in-progress: false

jobs:
  # ESLint and Prettier
  code-style:
    uses: ./.github/workflows/lint.yaml

  # TypeScript Typecheck and compiler checks
  typescript:
    uses: ./.github/workflows/typescript-typecheck.yaml

  # GraphQL Schema Publish
  graphql-schema:
    uses: ./.github/workflows/graphql-schema-publish.yaml
    secrets:
      hiveToken: ${{ secrets.HIVE_TOKEN }}
