name: on-mdx-change
on:
  pull_request:
    paths:
      # we run to check if the links are wrong
      - 'packages/web/docs/src/**/*.mdx'
      # or if a page disappeared
      - 'packages/web/docs/src/pages/**'
      - 'packages/web/docs/src/app/**'

jobs:
  validate-mdx-links:
    uses: the-guild-org/shared-config/.github/workflows/validate-mdx-links.yaml@main
    with:
      packageManager: pnpm
      cwd: packages/web/docs
      files: src/**/*.mdx
      version: '1.0.6'
    concurrency:
      group: mdx-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
