name: License Summary
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          codegen: false

      - name: generate license summary
        run: |
          npx license-checker --list > LICENSE_SUMMARY.txt

      - name: upload summary to action
        run: cat LICENSE_SUMMARY.txt >> $GITHUB_STEP_SUMMARY
