on:
  workflow_call:
    outputs:
      hivePublish:
        description: 'A boolean indicating whether hive pkg was published'
        value: ${{ jobs.publish.outputs.hivePublish }}
      hiveVersion:
        description: 'A semver version of the hive pkg, in case it was published'
        value: ${{ jobs.publish.outputs.hiveVersion }}
      cliPublish:
        description: 'A boolean indicating whether cli pkg was published'
        value: ${{ jobs.publish.outputs.cliPublish }}
      cliVersion:
        description: 'A semver version of the cli pkg, in case it was published'
        value: ${{ jobs.publish.outputs.cliVersion }}

jobs:
  publish:
    uses: ./.github/workflows/release-npm.yaml
    with:
      type: stable
    secrets:
      githubToken: ${{ secrets.BOT_GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
      hiveToken: ${{ secrets.HIVE_TOKEN }}
      r2AccessKeyId: ${{ secrets.R2_ACCESS_KEY_ID }}
      r2SecretAccessKey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
