name: 'Release Docker Images'

# When the workflow is invoked with a tag, we are releaseing the version.
on:
  workflow_call:
    inputs:
      tag:
        default: false
        type: string
        required: true

jobs:
  version:
    runs-on: ubuntu-22.04

    # Pass the version number to the next job
    outputs:
      number: ${{ steps.version.outputs.number }}

    steps:
      - name: extract version from tag
        id: version
        run: |
          # hive@1.0.0
          VERSION=${{ inputs.tag }}
          # 1.0.0
          VERSION_NUMBER=$(echo $VERSION | sed 's/[^0-9.]*//g')
          echo "number=$VERSION_NUMBER" >> $GITHUB_OUTPUT

  publish:
    needs: [version]
    if: ${{ contains(needs.version.outputs.number, '.') }}
    uses: ./.github/workflows/build-and-dockerize.yaml
    with:
      ref: refs/tags/${{ inputs.tag }}
      imageTag: ${{ needs.version.outputs.number }}
      publishLatest: true
      publishSourceMaps: true
      targets: build
      uploadJavaScriptArtifacts: true
    secrets: inherit
