on:
  workflow_call:

jobs:
  db-migrations:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14.11-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: registry
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: registry

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          codegen: false # no need to run codegen in this case, we can skip
          actor: migrations-test
          cacheNext: false
          cacheTurbo: false

      - name: migrations tests
        run: pnpm test
        working-directory: packages/migrations
