on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          actor: test-unit
          cacheNext: false
          cacheTurbo: false

      - name: unit tests
        run: pnpm test
