on:
  workflow_call:

jobs:
  typecheck:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          actor: typescript-typecheck

      - name: typecheck
        run: pnpm typecheck
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
