on:
  workflow_call:

jobs:
  typecheck:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          actor: ${{ github.workflow }}

      - name: typecheck
        run: pnpm typecheck
