on:
  workflow_call:

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          codegen: false
          actor: website

      - uses: the-guild-org/shared-config/website-cf@main
        name: build and deploy website
        env:
          NEXT_BASE_PATH: ${{ github.ref == 'refs/heads/main' && '/graphql/hive' || '' }}
          SITE_URL:
            ${{ github.ref == 'refs/heads/main' && 'https://the-guild.dev/graphql/hive' || '' }}
        with:
          cloudflareApiToken: ${{ secrets.WEBSITE_CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.WEBSITE_CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: hive-landing-page
          prId: ${{ github.event.pull_request.number }}
          mainBranch: main
          websiteDirectory: ./
          buildScript: cd packages/web/docs && pnpm build
          artifactDir: packages/web/docs/out
